# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8aa1190e8cc256cc3ece351e08e7e2b4ff1d7a28bdc0d6aecd9f8f4edbe70055c11bad7db14ef364cdddf8fdbfa73f983f760abfb72f5ef7b6dc373954d84c5a

test:
  secret_key_base: 34c44455dede0748add43bf20c68f3a9b79cdf3074607e7f2a928e68bf3fa54e36ace4f28af5c37d0e4c6d89fa03709053b3cd837c08105782833e766e66bdb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
